version: "3.8"

services:
  app:
    build:
      context: ./infrastructure/docker/php
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  web:
    image: nginx:latest
    container_name: laravel-web
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./infrastructure/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    platform: linux/amd64
    command: tunnel --url localhost:8080 --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db-data: